updates:
  - directory: /
    groups:
      busybox:
        patterns:
          - '@busybox/commitlint-config'
          - '@busybox/eslint-config'
          - '@busybox/prettier-config'
          - '@busybox/tsconfig'
          - '@busybox/cypress'
          - '@busybox/babel-preset-typescript'
      commitlint:
        patterns:
          - '@commitlint/cli'
          - commitlint
      nest-core:
        patterns:
          - '@nestjs/core'
          - '@nestjs/common'
          - '@nestjs/platform-express'
          - '@nestjs/testing'
      remix:
        patterns:
          - '@remix-run/react'
          - '@remix-run/dev'
          - '@remix-run/serve'
          - '@remix-run/node'
          - '@remix-run/css-bundle'
    ignore:
      - dependency-name: serialize-error
    package-ecosystem: npm
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
version: 2
