jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          node-version-file: .nvmrc
      - uses: actions/setup-python@v5
        with:
          python-version-file: systems/llm/.python-version
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
name: Verify PR
on: pull_request_target
